#!/usr/bin/env bash
# Reproduction script for lineage 14df351c56d65be8181299f225e5c266f35e6aded43dc8068b5f0e2e76ac622b
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/pytorch-CycleGAN-and-pix2pix reproduction
cd reproduction
git checkout 750f61d686adf84defe9e586c0a069b461d97770

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libfribidi0 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install GitPython==3.1.59 backports.tarfile==1.2.0 certifi==2026.7.22 charset-normalizer==3.5.0 dominate==2.9.1 gitdb==4.0.12 idna==3.18 more-itertools==10.8.0 mpmath==1.3.0 numpy==1.26.4 packaging==26.3 pillow==11.3.0 platformdirs==4.11.3 protobuf==6.33.6 pydantic==2.13.4 requests==2.34.2 sentry-sdk==2.68.0 setuptools==84.0.0 smmap==5.0.3 sympy==1.14.0 torch==2.4.0 torchvision==0.19.0 triton==3.0.0 urllib3==2.7.0 wandb==0.21.1

# 3. Run the pipeline (recorded order)
roar run bash ./datasets/download_pix2pix_dataset.sh facades
roar run python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA --n_epochs 1 --n_epochs_decay 1 --save_epoch_freq 1 --num_threads 0
roar put checkpoints/facades_pix2pix/latest_net_G.pth checkpoints/facades_pix2pix/latest_net_D.pth hf://reproducible-ai/pix2pix-facades --public --no-tag -m 'pix2pix Facades labels->photo, TRUNCATED to 2 of 200 epochs (1 constant-LR + 1 decay) over all 400 training pairs; checkpoint is NOT converged.'

