#!/usr/bin/env bash
# Reproduction script for lineage 58df327f1e02faf0d64efb8f07daac7c9eca70d3713d008bc8587fea780617be
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/cleanrl reproduction
cd reproduction
git checkout 99bb2870914fb8927d1441add96f8139c44927c2

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install Farama-Notifications==0.0.6 PyYAML==6.0.3 Pygments==2.20.0 absl-py==2.5.0 annotated-types==0.8.0 anyio==4.13.0 asttokens==3.0.1 blake3==1.0.9 boto3==1.42.96 botocore==1.42.96 brotli==1.2.0 certifi==2026.4.22 click==8.4.2 cryptography==50.0.0 decorator==5.2.1 defusedxml==0.7.1 dill==0.4.1 docstring_parser==0.18.0 executing==2.2.1 filelock==3.29.0 fsspec==2026.3.0 google-auth==2.49.2 gradio_client==2.5.0 gymnasium==0.29.1 h11==0.16.0 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.25.1 idna==3.13 ipython==9.13.0 jedi==0.19.2 jmespath==1.1.0 mpmath==1.3.0 networkx==3.6.1 numpy==2.4.4 nvidia-ml-py==13.595.45 orjson==3.11.9 packaging==26.2 parso==0.8.6 pillow==12.2.0 prompt_toolkit==3.0.52 protobuf==6.33.6 psutil==7.2.2 pure_eval==0.2.3 pydantic==2.13.4 pydantic_core==2.46.4 python-dateutil==2.9.0.post0 python-multipart==0.0.32 rich==15.0.0 s3transfer==0.16.1 six==1.17.0 stack-data==0.6.3 starlette==1.0.0 sympy==1.14.0 tabulate==0.10.0 tensorboard==2.21.0 torch==2.7.0 tqdm==4.67.3 trackio==0.33.0 traitlets==5.14.3 triton==3.3.0 typing-inspection==0.4.2 typing_extensions==4.16.0 tyro==1.0.15 urllib3==2.6.3 uvicorn==0.46.0 watchfiles==1.2.0 wcwidth==0.6.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run --wandb-to-trackio python cleanrl/ppo.py --env-id CartPole-v1 --seed 1 --total-timesteps 500000 --track --wandb-project-name cleanrl-ppo-cartpole --save-model --model-path out/ppo_cartpole.cleanrl_model
roar put out/ppo_cartpole.cleanrl_model hf://reproducible-ai/cleanrl-ppo --public --no-tag -m 'CleanRL ppo.py on CartPole-v1, upstream default hyperparameters, 500k timesteps (full default run)'

