#!/usr/bin/env bash
# Reproduction script for lineage 0c119a28e8d9d48dc2fa9ec8714a266109bd45dce6b2e70527fa6b2772d5fd3e
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/nerf-pytorch.git reproduction
cd reproduction
git checkout b7647e3a785c244c56de9ce7afeb9d17012cbc3d

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libbsd0 libffi8 libglib2.0-0 libmd0 libsqlite3-0 libssl3 libstdc++6 libuuid1 libx11-6 libxau6 libxcb1 libxdmcp6 libxext6
pip install ConfigArgParse==1.7.5 ImageIO==2.37.3 PyYAML==6.0.3 annotated-types==0.7.0 blake3==1.0.9 click==8.4.2 cryptography==46.0.7 cycler==0.12.1 defusedxml==0.7.1 dill==0.4.1 filelock==3.29.0 imageio-ffmpeg==0.6.0 kiwisolver==1.5.0 matplotlib==3.10.9 mpmath==1.3.0 networkx==3.6.1 numpy==2.4.4 nvidia-ml-py==13.595.45 opencv-python==5.0.0.93 packaging==26.2 pillow==12.2.0 pydantic==2.13.3 pydantic_core==2.46.3 pyparsing==3.3.2 python-dateutil==2.9.0.post0 six==1.17.0 sympy==1.14.0 tabulate==0.10.0 torch==2.7.0 tqdm==4.67.3 triton==3.3.0 typing-inspection==0.4.2 typing_extensions==4.15.0 wcwidth==0.6.0

# 3. Run the pipeline (recorded order)
roar run python repro/fetch_example_data.py --out-dir data
roar run python repro/train_truncated.py --train-iters 2000 --config configs/lego.txt --i_weights 2000
roar run python run_nerf.py --config configs/lego.txt --render_only --render_test --render_factor 8
roar put logs/blender_paper_lego/002000.tar hf://reproducible-ai/nerf-pytorch-lego --public --no-tag -m 'NeRF fit to the lego scene of the NeRF synthetic dataset (400x400, half_res), 2000 of upstream'"'"'s hardcoded 200000 iterations. TRUNCATED pipeline-viability run: NOT converged and not a quality result.'

