#!/usr/bin/env bash
# Reproduction script for lineage bd03ccc719095e91b2e622dc7964d2f74909783b4930b95d1833177cbaa87775
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
# Publish (roar put) steps are omitted (--no-puts).
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/FlagEmbedding reproduction
cd reproduction
git checkout 42b0108abb4f844e7d6adf762e1848c71e8685a1

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install Jinja2==3.1.6 MarkupSafe==3.0.3 PyYAML==6.0.3 accelerate==1.2.1 aiohappyeyeballs==2.7.1 aiohttp==3.14.3 aiosignal==1.4.0 attrs==26.1.0 backports.tarfile==1.2.0 certifi==2026.7.22 charset-normalizer==3.5.1 cloudpickle==3.1.2 datasets==3.2.0 dill==0.3.8 filelock==3.32.5 frozenlist==1.8.0 fsspec==2024.9.0 hf-xet==1.6.0 huggingface_hub==0.36.2 idna==3.19 joblib==1.6.0 lz4==4.4.5 more-itertools==10.8.0 mpmath==1.3.0 multidict==6.7.1 multiprocess==0.70.16 narwhals==2.25.0 numpy==2.5.2 packaging==26.3 pandas==3.0.5 peft==0.14.0 pillow==12.3.0 propcache==0.5.2 psutil==7.2.2 pyarrow==25.0.1 python-dateutil==2.9.0.post0 requests==2.34.2 safetensors==0.8.0 scikit-learn==1.9.0 scipy==1.18.1 setuptools==84.0.0 six==1.17.0 sympy==1.13.1 threadpoolctl==3.6.0 tokenizers==0.21.4 torch==2.5.1 tqdm==4.70.0 transformers==4.48.3 triton==3.1.0 typing_extensions==4.16.0 urllib3==2.7.0 xxhash==4.0.1 yarl==1.24.5

# 3. Run the pipeline (recorded order)
roar run env PYTHONUNBUFFERED=1 python -m FlagEmbedding.finetune.embedder.encoder_only.base --model_name_or_path prajjwal1/bert-tiny --cache_dir bge-finetune-cache/model --train_data examples/finetune/embedder/example_data/retrieval/nli.jsonl --cache_path bge-finetune-cache/data --train_group_size 2 --query_max_len 32 --passage_max_len 64 --output_dir bge-finetune-output --overwrite_output_dir --learning_rate 1e-5 --max_steps 1 --per_device_train_batch_size 1 --dataloader_drop_last false --dataloader_num_workers 0 --logging_steps 1 --save_steps 1 --seed 43 --sentence_pooling_method cls --normalize_embeddings true --report_to none

