#!/usr/bin/env bash
# Reproduction script for lineage f81176e64bf814489ec3296286e11c499a48ca28ef52569e10bc2675c0780782
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/Depth-Anything-V2.git reproduction
cd reproduction
git checkout 02dc493d42843827f8a1af1a3d4e447bc03721ac

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): ibverbs-providers libfabric1-aws libffi8 libfribidi0 libgdrapi libhwloc15 libibverbs1 libnccl-ofi libnl-route-3-200 libsqlite3-0 libssl3 libstdc++6 libudev1 libuuid1
pip install PyYAML==6.0.3 Pygments==2.20.0 absl-py==2.5.0 annotated-types==0.7.0 anyio==4.13.0 blake3==1.0.9 boto3==1.42.96 botocore==1.42.96 brotli==1.2.0 certifi==2026.4.22 charset-normalizer==3.4.7 click==8.4.2 cryptography==46.0.7 defusedxml==0.7.1 dill==0.4.1 filelock==3.29.0 fsspec==2026.3.0 google-auth==2.49.2 h11==0.16.0 h5py==3.16.0 hf-xet==1.5.2 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.25.1 idna==3.13 jmespath==1.1.0 mpmath==1.3.0 networkx==3.6.1 numpy==1.26.4 nvidia-ml-py==13.595.45 opencv-python-headless==4.11.0.86 pillow==12.2.0 protobuf==6.33.6 pydantic==2.13.3 pydantic_core==2.46.3 python-dateutil==2.9.0.post0 remotezip==0.12.3 requests==2.33.1 rich==14.3.4 s3transfer==0.16.1 six==1.17.0 sympy==1.14.0 tabulate==0.10.0 tensorboard==2.21.0 torch==2.7.0 torchvision==0.22.0 tqdm==4.67.3 triton==3.3.0 typing-inspection==0.4.2 typing_extensions==4.15.0 urllib3==2.6.3 wcwidth==0.6.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run env -C metric_depth python repro_fetch_pretrained.py --encoder vits
roar run env -C metric_depth python repro_prepare_hypersim_slice.py --train-frames 64 --val-frames 16
roar run env -C metric_depth RANK=0 WORLD_SIZE=1 LOCAL_RANK=0 MASTER_ADDR=127.0.0.1 MASTER_PORT=29500 python train.py --epochs 1 --encoder vits --bs 4 --lr 0.000005 --save-path exp/hypersim --dataset hypersim --img-size 518 --min-depth 0.001 --max-depth 20 --pretrained-from ../checkpoints/depth_anything_v2_vits.pth --port 29500
roar put metric_depth/exp/hypersim/latest.pth hf://reproducible-ai/depth-anything-v2 --public --no-tag -m 'Depth Anything V2 metric depth, ViT-S encoder, fine-tuned 1 epoch on a 64-image Hypersim slice. TRUNCATED and not converged: upstream trains 120 epochs on the full 59543-image split across 8 GPUs.'

