#!/usr/bin/env bash
# Reproduction script for lineage c7e6843763c25d8036ff22e48ba43a12d0dd0051d016f1f1e0090a88a3e99453
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
# Publish (roar put) steps are omitted (--no-puts).
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/diffusers reproduction
cd reproduction
git checkout 0af4dfdfc2cd401182580109cca05cb5ada3ed17

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libfribidi0 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install PyYAML==6.0.3 Pygments==2.20.0 accelerate==1.14.0 aiohappyeyeballs==2.6.1 aiohttp==3.13.5 aiosignal==1.4.0 annotated-types==0.8.0 anyio==4.13.0 asttokens==3.0.1 attrs==26.1.0 blake3==1.0.9 boto3==1.42.96 botocore==1.42.96 brotli==1.2.0 certifi==2026.4.22 charset-normalizer==3.4.7 click==8.4.2 cloudpickle==3.1.2 cryptography==50.0.0 datasets==5.0.1 decorator==5.2.1 defusedxml==0.7.1 dill==0.4.1 executing==2.2.1 filelock==3.29.0 frozenlist==1.8.0 fsspec==2026.3.0 gradio_client==2.5.0 h11==0.16.0 hf-xet==1.5.2 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.27.0 idna==3.13 ipython==9.13.0 jedi==0.19.2 jmespath==1.1.0 mpmath==1.3.0 multidict==6.7.1 multiprocess==0.70.19 networkx==3.6.1 numpy==2.4.4 nvidia-ml-py==13.595.45 orjson==3.11.9 packaging==26.2 pandas==2.3.3 parso==0.8.6 pillow==12.2.0 prompt_toolkit==3.0.52 propcache==0.4.1 psutil==7.2.2 pure_eval==0.2.3 pyarrow==23.0.1 pydantic==2.13.4 pydantic_core==2.46.4 python-dateutil==2.9.0.post0 python-multipart==0.0.32 pytz==2026.1.post1 requests==2.33.1 rich==15.0.0 s3transfer==0.16.1 safetensors==0.8.0 scipy==1.17.1 six==1.17.0 stack-data==0.6.3 starlette==1.0.0 sympy==1.14.0 tabulate==0.10.0 threadpoolctl==3.6.0 torch==2.7.0 torchvision==0.22.0 tqdm==4.67.3 trackio==0.33.0 traitlets==5.14.3 triton==3.3.0 typing-inspection==0.4.2 typing_extensions==4.16.0 urllib3==2.6.3 uvicorn==0.46.0 wandb==0.28.1 watchfiles==1.2.0 wcwidth==0.6.0 xxhash==3.8.1 yarl==1.23.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run --wandb-to-trackio sh -c 'PYTHONPATH=src:$PYTHONPATH exec python examples/unconditional_image_generation/train_unconditional.py --dataset_name=huggan/pokemon --cache_dir=data --resolution=64 --center_crop --random_flip --output_dir=ddpm-out --train_batch_size=16 --num_epochs=1 --save_images_epochs=1 --save_model_epochs=1 --gradient_accumulation_steps=1 --use_ema --learning_rate=1e-4 --lr_warmup_steps=10 --mixed_precision=no --logger=wandb --dataloader_num_workers=0 --ddpm_num_inference_steps=10 --eval_batch_size=4 --checkpointing_steps=100000'

