#!/usr/bin/env bash
# Reproduction script for lineage 3b9c6606967c1008bc75ef5d5c83b8df4e6ea6183967eaee596329e324f47647
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
# Publish (roar put) steps are omitted (--no-puts).
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/litgpt reproduction
cd reproduction
git checkout fe35987736e1163a6f91b7e67e64527f4c12dd1e

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# Build tool packages (apt; requires sudo): binutils
# System packages (apt; requires sudo): libffi8 libfribidi0 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install Jinja2==3.1.6 MarkupSafe==3.0.3 PyYAML==6.0.3 annotated-types==0.7.0 attrs==26.1.0 bcrypt==5.0.0 blake3==1.0.9 boto3==1.42.96 botocore==1.42.96 brotli==1.2.0 certifi==2026.4.22 charset-normalizer==3.4.7 click==8.4.2 cryptography==46.0.7 cycler==0.12.1 defusedxml==0.7.1 dill==0.4.1 docstring_parser==0.18.0 filelock==3.29.0 fsspec==2026.3.0 huggingface_hub==0.36.2 idna==3.13 jmespath==1.1.0 jsonargparse==4.41.0 kiwisolver==1.5.0 lightning-utilities==0.15.3 lightning==2.6.5 litdata==0.2.59 matplotlib==3.10.9 mpmath==1.3.0 networkx==3.6.1 numpy==2.4.4 nvidia-ml-py==13.595.45 packaging==26.2 pillow==12.2.0 psutil==7.2.2 pydantic==2.13.3 pydantic_core==2.46.3 pyparsing==3.3.2 python-dateutil==2.9.0.post0 requests==2.33.1 rich==14.3.4 s3fs==0.4.2 s3transfer==0.16.1 safetensors==0.8.0 scipy==1.17.1 six==1.17.0 sympy==1.14.0 tabulate==0.10.0 tifffile==2026.7.31 tokenizers==0.23.1 torch==2.7.0 torchmetrics==1.9.0 torchvision==0.22.0 tqdm==4.67.3 triton==3.3.0 typeshed_client==2.13.0 typing-inspection==0.4.2 typing_extensions==4.15.0 urllib3==2.6.3 wcwidth==0.6.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run python -m litgpt download EleutherAI/pythia-14m --tokenizer_only true
roar run curl -fsSL --create-dirs -o data_train/wikitext2_train.txt https://raw.githubusercontent.com/pytorch/examples/main/word_language_model/data/wikitext-2/train.txt -o data_val/wikitext2_valid.txt https://raw.githubusercontent.com/pytorch/examples/main/word_language_model/data/wikitext-2/valid.txt
roar run python -m reproduction.prepare_data --train_data_path data_train --val_data_path data_val --tokenizer_dir checkpoints/EleutherAI/pythia-14m --micro_batch_size 1 --max_seq_length 128
roar run python -m litgpt pretrain pythia-14m --tokenizer_dir checkpoints/EleutherAI/pythia-14m --data TextFiles --data.train_data_path data_train --data.val_data_path data_val --data.num_workers 0 --out_dir out --logger_name csv --devices 1 --seed 42 --train.max_tokens 2048 --train.max_seq_length 128 --train.micro_batch_size 1 --train.global_batch_size 2 --train.lr_warmup_steps 1 --train.log_interval 1 --train.save_interval 1000 --train.max_norm 1.0 --eval.interval 1000 --eval.max_iters 2 --eval.final_validation true

