#!/usr/bin/env bash
# Reproduction script for lineage fd445b9abb32632e4b3c6ca4c97a1e8a868233c4abb794d2ed94af1ce2f920b2
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/s4 reproduction
cd reproduction
git checkout b0878a68ab8651eef3f69802b305df87cd718c9e

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libfribidi0 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install PyNaCl==1.6.2 PyYAML==6.0.3 Pygments==2.20.0 absl-py==2.5.0 aiohappyeyeballs==2.6.1 aiohttp==3.13.5 aiosignal==1.4.0 annotated-types==0.7.0 antlr4-python3-runtime==4.9.3 anyio==4.13.0 attrs==26.1.0 audioread==3.1.0 backports.tarfile==1.2.0 bcrypt==5.0.0 blake3==1.0.9 boto3==1.42.96 botocore==1.42.96 brotli==1.2.0 certifi==2026.4.22 charset-normalizer==3.4.7 click==8.4.2 cloudpickle==3.1.2 cryptography==46.0.7 cycler==0.12.1 datasets==5.0.1 decorator==5.2.1 defusedxml==0.7.1 dill==0.4.1 einops==0.8.2 filelock==3.29.0 frozenlist==1.8.0 fsspec==2026.3.0 google-auth==2.49.2 h11==0.16.0 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.25.1 hydra-core==1.3.5 idna==3.13 invoke==3.0.3 jmespath==1.1.0 joblib==1.5.3 kiwisolver==1.5.0 librosa==0.9.2 lightning-utilities==0.15.3 llvmlite==0.47.0 matplotlib==3.9.4 ml_dtypes==0.5.4 more-itertools==11.1.0 mpmath==1.3.0 multidict==6.7.1 multiprocess==0.70.19 narwhals==2.20.0 numba==0.65.1 numpy==1.26.4 nvidia-ml-py==13.595.45 omegaconf==2.3.1 onnx-ir==0.2.1 onnx==1.21.0 onnxruntime==1.25.0 onnxscript==0.3.1 packaging==26.2 pandas==3.0.5 paramiko==4.0.0 pillow==12.3.0 platformdirs==4.9.6 pooch==1.9.0 propcache==0.4.1 protobuf==6.33.6 psutil==7.2.2 pyarrow==23.0.1 pydantic==2.13.3 pydantic_core==2.46.3 pyparsing==3.3.2 python-dateutil==2.9.0.post0 pytorch-lightning==2.0.4 pytz==2026.1.post1 requests==2.33.1 resampy==0.4.3 rich==13.9.4 s3transfer==0.16.1 scikit-learn==1.9.0 scipy==1.13.1 setuptools==75.8.0 six==1.17.0 soundfile==0.14.0 sympy==1.14.0 tabulate==0.10.0 tensorboard==2.21.0 threadpoolctl==3.6.0 torch==2.3.0 torchaudio==2.3.0 torchmetrics==1.9.0 torchtext==0.18.0 torchvision==0.18.0 tqdm==4.70.0 typing-inspection==0.4.2 typing_extensions==4.15.0 urllib3==2.6.3 wandb==0.28.1 wcwidth==0.6.0 xxhash==3.8.1 yarl==1.23.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run python -m train pipeline=mnist dataset.permute=True model=s4 model.n_layers=3 model.d_model=128 model.norm=batch model.prenorm=True wandb=null trainer.max_epochs=1 loader.num_workers=0 hydra.run.dir=./outputs/run
roar put outputs/run/checkpoints/val/accuracy.ckpt hf://reproducible-ai/s4-smnist --public --no-tag -m 'S4 on permuted sequential MNIST — TRUNCATED: 1 of 200 epochs (configs/trainer/default.yaml), not converged'

