#!/usr/bin/env bash
# Reproduction script for lineage 847b359a9f1a0ae3a31a621f9901f57e5387f37610adabc9e7bd24f4ecdae97d
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/Kronos reproduction
cd reproduction
git checkout a6ba0bd27d70e1c6e666a6d74ae74f8b718e9a7b

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install Jinja2==3.1.6 MarkupSafe==3.0.3 PyYAML==6.0.3 annotated-types==0.7.0 blake3==1.0.9 brotli==1.2.0 certifi==2026.4.22 charset-normalizer==3.4.7 click==8.4.2 cloudpickle==3.1.2 cryptography==46.0.7 dill==0.4.1 einops==0.8.1 filelock==3.29.0 google-auth==2.49.2 hf-xet==1.5.2 huggingface-hub==0.33.1 idna==3.13 ml_dtypes==0.5.4 mpmath==1.3.0 numpy==1.26.4 nvidia-ml-py==13.595.45 onnx-ir==0.2.1 onnx==1.21.0 onnxruntime==1.25.0 onnxscript==0.3.1 packaging==26.2 pandas==2.2.2 protobuf==6.33.6 pyarrow==23.0.1 pydantic==2.13.3 pydantic_core==2.46.3 python-dateutil==2.9.0.post0 pytz==2026.1.post1 requests==2.33.1 safetensors==0.6.2 six==1.17.0 sympy==1.14.0 tabulate==0.10.0 torch==2.3.0 tqdm==4.67.1 typing-inspection==0.4.2 typing_extensions==4.15.0 urllib3==2.6.3 wcwidth==0.6.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run python repro/fetch_pretrained.py
roar run env -C finetune_csv python train_sequential.py --config configs/config_repro_kronos-small_1epoch.yaml --skip-basemodel
roar run env -C finetune_csv python train_sequential.py --config configs/config_repro_kronos-small_1epoch.yaml --skip-tokenizer
roar put finetune_csv/finetuned/HK_ali_09988_kline_5min_all/basemodel/best_model/model.safetensors hf://reproducible-ai/kronos --public --no-tag -m 'Kronos-small fine-tuned on HK 09988 5-min K-lines, TRUNCATED to 1 epoch of tokenizer + 1 epoch of predictor (upstream defaults 30 / 20); not converged'

