#!/usr/bin/env bash
# Reproduction script for lineage 0bc12b45d58b9d1657f3d39f770ae43659612cfdabc55be6e138af3358924d01
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/examples.git reproduction
cd reproduction
git checkout 4902d7199692c8707edb54759cfc1d627ce94225

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libfribidi0 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install filelock==3.32.5 mpmath==1.3.0 networkx==3.6.1 numpy==2.2.6 pillow==11.3.0 sympy==1.14.0 torch==2.7.0 torchvision==0.22.0 triton==3.3.0 typing_extensions==4.16.0

# 3. Run the pipeline (recorded order)
roar run sh -c 'set -eu; mkdir -p fast_neural_style/out-data; curl -fL -o fast_neural_style/out-data/imagenette2-320.tgz https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-320.tgz; echo "569b4497c98db6dd29f335d1f109cf315fe127053cedf69010d047f0188e158c  fast_neural_style/out-data/imagenette2-320.tgz" | sha256sum -c -; tar -xzf fast_neural_style/out-data/imagenette2-320.tgz -C fast_neural_style/out-data'
roar run env -C fast_neural_style python neural_style/neural_style.py train --dataset out-data/imagenette2-320/train --style-image images/style-images/mosaic.jpg --save-model-dir out-model --checkpoint-model-dir out-ckpt --epochs 1 --batch-size 4 --checkpoint-interval 2368 --accel
roar run env -C fast_neural_style python neural_style/neural_style.py eval --content-image images/content-images/amber.jpg --model out-ckpt/ckpt_epoch_0_batch_id_2368.pth --output-image out-stylized/amber-mosaic.jpg --accel
roar put fast_neural_style/out-ckpt/ckpt_epoch_0_batch_id_2368.pth fast_neural_style/out-stylized/amber-mosaic.jpg hf://reproducible-ai/fast-neural-style --public --no-tag -m 'TRUNCATED: one of the upstream default two epochs on Imagenette-320; pipeline viability only, not converged.'

