#!/usr/bin/env bash
# Reproduction script for lineage acc9448d8d05c85402418424a7f9aa3da9bd539755554ba8442d95092d1bdad7
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/distil-whisper reproduction
cd reproduction
git checkout 5164ee1bcca097f05837faec983615de6e4c281a

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install PyYAML==6.0.3 RapidFuzz==3.14.5 accelerate==0.31.0 aiohappyeyeballs==2.7.1 aiohttp==3.14.3 aiosignal==1.4.0 attrs==26.1.0 audioread==3.1.0 certifi==2026.7.22 cffi==2.1.1 charset-normalizer==3.5.1 click==8.5.0 datasets==2.19.2 decorator==5.3.1 dill==0.3.8 evaluate==0.4.2 filelock==3.32.4 frozenlist==1.8.0 fsspec==2024.3.1 hf-xet==1.6.0 huggingface_hub==0.36.2 idna==3.19 jiwer==3.0.4 joblib==1.5.3 lazy-loader==0.5 librosa==0.11.0 llvmlite==0.49.0 mpmath==1.3.0 msgpack==1.2.2 multidict==6.7.1 multiprocess==0.70.16 narwhals==2.25.0 numba==0.67.0 numpy==1.26.4 packaging==26.3 pandas==3.0.5 platformdirs==4.11.5 pooch==1.9.0 propcache==0.5.2 psutil==7.2.2 pyarrow-hotfix==0.7 pyarrow==25.0.1 pycparser==3.0 python-dateutil==2.9.0.post0 regex==2026.7.19 requests==2.34.2 safetensors==0.8.0 scikit-learn==1.9.0 scipy==1.17.1 six==1.17.0 soundfile==0.14.0 soxr==1.1.0 sympy==1.14.0 threadpoolctl==3.6.0 tokenizers==0.19.1 torch==2.3.0 tqdm==4.70.0 transformers==4.41.2 typing_extensions==4.16.0 urllib3==2.7.0 xxhash==4.0.1 yarl==1.24.5

# 3. Run the pipeline (recorded order)
roar run --wandb-to-trackio python training/create_student_model.py --teacher_checkpoint openai/whisper-tiny.en --encoder_layers 4 --decoder_layers 1 --save_dir distil-tiny-en-init --cache_dir model-cache
roar run --wandb-to-trackio env WANDB_MODE=offline WANDB_SILENT=true TOKENIZERS_PARALLELISM=false python training/run_distillation.py --model_name_or_path distil-tiny-en-init --teacher_model_name_or_path openai/whisper-tiny.en --cache_dir model-cache --dataset_cache_dir dataset-cache --train_dataset_name hf-internal-testing/librispeech_asr_dummy --train_dataset_config_name clean --train_split_name validation --text_column_name text --eval_dataset_name hf-internal-testing/librispeech_asr_dummy --eval_dataset_config_name clean --eval_split_name validation --eval_text_column_name text --use_pseudo_labels False --streaming False --max_train_samples 2 --max_eval_samples 1 --max_steps 1 --eval_steps 1 --save_steps 1 --logging_steps 1 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --dataloader_num_workers 0 --preprocessing_num_workers 1 --dtype float32 --output_dir distil-tiny-en --do_train --do_eval --predict_with_generate --freeze_encoder --overwrite_output_dir --report_to wandb --wandb_project reproducible-ai-distil-whisper --wandb_name row-013-capture --wandb_dir wandb
roar put distil-tiny-en/end-of-training-weights/model.safetensors hf://reproducible-ai/distil-whisper --public --no-tag -m 'Truncated one-step Distil-Whisper training record; no convergence claim.'

