#!/usr/bin/env bash
# Reproduction script for lineage 27064dbb01d6fa6e241329f93deff5e224eba4400482790adaabf52955be91fb
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/lerobot reproduction
cd reproduction
git checkout 8cdbf8c226b80293d1692feb11cc767e1d4df531

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libfribidi0 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install Farama-Notifications==0.0.6 PyYAML==6.0.3 Pygments==2.20.0 accelerate==1.14.0 aiohappyeyeballs==2.6.1 aiohttp==3.13.5 aiosignal==1.4.0 annotated-types==0.7.0 anyio==4.13.0 asttokens==3.0.1 attrs==26.1.0 av==15.1.0 blake3==1.0.9 boto3==1.42.96 botocore==1.42.96 brotli==1.2.0 certifi==2026.4.22 charset-normalizer==3.4.7 click==8.4.2 cloudpickle==3.1.2 cryptography==46.0.7 datasets==4.8.5 decorator==5.2.1 deepdiff==9.0.0 defusedxml==0.7.1 dill==0.4.1 draccus==0.11.6 einops==0.8.2 executing==2.2.1 filelock==3.29.0 frozenlist==1.8.0 fsspec==2026.2.0 gradio_client==2.5.0 gymnasium==1.3.0 h11==0.16.0 hf-xet==1.5.2 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.25.1 idna==3.13 ipython==9.13.0 jedi==0.19.2 jmespath==1.1.0 mergedeep==1.3.4 mpmath==1.3.0 multidict==6.7.1 multiprocess==0.70.19 mypy_extensions==1.1.0 networkx==3.6.1 numpy==2.2.6 nvidia-ml-py==13.595.45 opencv-python-headless==4.13.0.92 orderly-set==5.5.0 orjson==3.11.9 packaging==25.0 pandas==2.3.3 parso==0.8.6 pillow==12.2.0 prompt_toolkit==3.0.52 propcache==0.4.1 psutil==7.2.2 pure_eval==0.2.3 pyarrow==23.0.1 pydantic==2.13.3 pydantic_core==2.46.3 python-dateutil==2.9.0.post0 python-multipart==0.0.32 pytz==2026.1.post1 requests==2.33.1 rich==14.3.4 s3transfer==0.16.1 safetensors==0.8.0 scipy==1.17.1 six==1.17.0 stack-data==0.6.3 starlette==1.0.0 sympy==1.14.0 tabulate==0.10.0 termcolor==3.3.0 threadpoolctl==3.6.0 torch==2.7.0 torchcodec==0.4.0 torchvision==0.22.0 tqdm==4.67.3 trackio==0.33.0 traitlets==5.14.3 triton==3.3.0 typing-inspect==0.9.0 typing-inspection==0.4.2 typing_extensions==4.15.0 urllib3==2.6.3 uvicorn==0.46.0 wandb==0.27.2 watchfiles==1.2.0 wcwidth==0.6.0 xxhash==3.8.1 yarl==1.23.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run python repro/fetch_dataset.py --repo-id lerobot/pusht_image --out-dir data/pusht_image
roar run --wandb-to-trackio env TRACKIO_SPACE_ID=reproducible-ai/experiments python repro/train_act.py --dataset.repo_id=lerobot/pusht_image --dataset.root=data/pusht_image --dataset.eval_split=0.1 --policy.type=act --policy.device=cuda --policy.push_to_hub=false --steps=300 --batch_size=8 --num_workers=0 --log_freq=25 --eval_steps=150 --env_eval_freq=0 --save_freq=-1 --seed=1000 --output_dir=outputs/act_pusht --job_name=act_pusht_truncated --wandb.enable=true --wandb.project=lerobot-act-pusht --wandb.disable_artifact=true
roar run python repro/evaluate_act.py --checkpoint outputs/act_pusht/checkpoints/000300/pretrained_model --repo-id lerobot/pusht_image --root data/pusht_image --eval-split 0.1 --batch-size 8 --device cuda --out metrics/metrics.json
roar put outputs/act_pusht/checkpoints/000300/pretrained_model/model.safetensors hf://reproducible-ai/lerobot-act --public --no-tag -m 'ACT policy (Action Chunking Transformer, ResNet-18 backbone) trained on the public lerobot/pusht_image LeRobotDataset: 300 of the 100000 default training steps, batch size 8. TRUNCATED pipeline-viability run, NOT converged and not a quality result.'

