#!/usr/bin/env bash
# Reproduction script for lineage 357518abae1151de0ba348a507715a48c44688e705a3039aa49e293c989c095d
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
# Publish (roar put) steps are omitted (--no-puts).
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/RWKV-LM reproduction
cd reproduction
git checkout 2fd4c778521b391f537c61d607a51f3eba35f183

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# Build tool packages (apt; requires sudo): binutils
# System packages (apt; requires sudo): ibverbs-providers libfabric1-aws libffi8 libgdrapi libhwloc15 libibverbs1 libnccl-ofi libnl-route-3-200 libsqlite3-0 libssl3 libstdc++6 libudev1 libuuid1
pip install PyYAML==6.0.3 annotated-types==0.8.0 anyio==4.14.2 brotli==1.2.0 certifi==2026.7.22 click==8.5.0 cuda-bindings==13.3.1 cuda-pathfinder==1.8.0 deepspeed==0.17.6 einops==0.8.2 filelock==3.32.5 fsspec==2026.7.0 gradio_client==2.6.1 h11==0.16.0 hjson==3.1.0 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.29.0 idna==3.19 lightning-utilities==0.15.3 more-itertools==10.3.0 mpmath==1.3.0 msgpack==1.2.2 networkx==3.6.1 ninja==1.13.0 numpy==1.26.4 orjson==3.12.0 packaging==26.3 pillow==12.3.0 platformdirs==4.11.6 psutil==7.2.2 py-cpuinfo==9.0.0 pydantic==2.13.5 pydantic_core==2.46.5 python-multipart==0.0.32 pytorch-lightning==1.9.5 setuptools==80.9.0 starlette==1.6.0 sympy==1.14.0 torch==2.13.0 torchmetrics==1.9.0 tqdm==4.70.0 trackio==0.37.0 triton==3.7.1 typing-inspection==0.4.4 typing_extensions==4.16.0 uvicorn==0.52.4 wandb==0.21.1 watchfiles==1.2.0

# 3. Run the pipeline (recorded order)
roar run --wandb-to-trackio env TRACKIO_SPACE_ID=reproducible-ai/experiments python campaign/download_minipile.py
roar run --wandb-to-trackio env -C RWKV-v7/train_temp TRACKIO_SPACE_ID=reproducible-ai/experiments python train.py --wandb '' --proj_dir out/L12-D768-x070 --data_file data/minipile --data_type binidx --vocab_size 65536 --my_testing x070 --ctx_len 512 --train_stage 1 --epoch_count 1 --epoch_begin 0 --epoch_save 1 --weight_decay 0 --head_size 64 --num_nodes 1 --micro_bsz 1 --n_layer 12 --n_embd 768 --my_exit_tokens 1498226207 --magic_prime 2926181 --lr_init 1e-5 --lr_final 1e-5 --warmup_steps 10 --beta1 0.9 --beta2 0.99 --adam_eps 1e-8 --accelerator cpu --devices 1 --precision bf16 --strategy deepspeed_stage_2 --grad_cp 1
roar run --wandb-to-trackio sh -c 'exec env -C RWKV-v7/train_temp TRACKIO_SPACE_ID=reproducible-ai/experiments python train.py --load_model 0 --wandb rwkv-7-minipile --proj_dir out/L12-D768-x070 --my_testing x070 --ctx_len 512 --train_stage 3 --epoch_count 999999 --epoch_begin 0 --data_file data/minipile --my_exit_tokens 1498226207 --magic_prime 2926181 --num_nodes 1 --micro_bsz 16 --n_layer 12 --n_embd 768 --kernel @rwkv3 --lr_init 6e-4 --lr_final 6e-5 --warmup_steps 10 --beta1 0.9 --beta2 0.99 --adam_eps 1e-18 --data_type binidx --vocab_size 65536 --weight_decay 0.001 --epoch_save 1 --head_size 64 --head_chunk 0 --accelerator gpu --devices 1 --precision bf16 --strategy deepspeed_stage_2 --grad_cp 1 --enable_progress_bar True --max_steps 2'

