#!/usr/bin/env bash
# Reproduction script for lineage af56b02d6c041c931f03ccf643f2e0fee97bbddb0072f26b91a291f142850dfd
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/pytorch-image-models reproduction
cd reproduction
git checkout f741a2b0a1a189a4ecb94793fa54deb9912a7c2c

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libfribidi0 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install PyYAML==6.0.3 Pygments==2.20.0 annotated-types==0.7.0 anyio==4.13.0 asttokens==3.0.1 blake3==1.0.9 brotli==1.2.0 certifi==2026.4.22 charset-normalizer==3.4.7 click==8.4.2 cloudpickle==3.1.2 cryptography==46.0.7 decorator==5.2.1 defusedxml==0.7.1 dill==0.4.1 executing==2.2.1 filelock==3.29.0 fsspec==2026.3.0 gradio_client==2.5.0 h11==0.16.0 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.25.1 idna==3.13 ipython==9.13.0 jedi==0.19.2 joblib==1.5.3 mpmath==1.3.0 networkx==3.6.1 numpy==2.4.4 nvidia-ml-py==13.595.45 orjson==3.11.9 packaging==26.2 pandas==2.3.3 parso==0.8.6 pillow==12.2.0 prompt_toolkit==3.0.52 psutil==7.2.2 pure_eval==0.2.3 pyarrow==23.0.1 pydantic==2.13.3 pydantic_core==2.46.3 python-dateutil==2.9.0.post0 python-multipart==0.0.32 pytz==2026.1.post1 rich==14.3.4 safetensors==0.8.0 scikit-learn==1.8.0 scipy==1.17.1 six==1.17.0 stack-data==0.6.3 starlette==1.0.0 sympy==1.14.0 tabulate==0.10.0 threadpoolctl==3.6.0 torch==2.7.0 torchvision==0.22.0 tqdm==4.67.3 trackio==0.33.0 traitlets==5.14.3 triton==3.3.0 typing-inspection==0.4.2 typing_extensions==4.15.0 uvicorn==0.46.0 watchfiles==1.2.0 wcwidth==0.6.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run --wandb-to-trackio python reproduction/fetch_fashion_mnist.py --data-dir ./data
roar run --wandb-to-trackio python train.py --data-dir ./data --dataset torch/fashion_mnist --train-split train --val-split validation --model resnet18 --num-classes 10 --in-chans 1 --img-size 28 --mean 0.2860 --std 0.3530 --batch-size 256 --epochs 5 --warmup-epochs 0 --opt sgd --lr 0.05 --weight-decay 5e-4 --sched cosine --workers 0 --seed 42 --save-last-only --output ./output --experiment resnet18-fashion-mnist --log-wandb --wandb-project resnet18-fashion-mnist
roar run --wandb-to-trackio python validate.py --data-dir ./data --dataset torch/fashion_mnist --split validation --model resnet18 --num-classes 10 --in-chans 1 --img-size 28 --mean 0.2860 --std 0.3530 --crop-pct 1.0 --batch-size 256 --workers 0 --checkpoint ./output/resnet18-fashion-mnist/last.pth.tar --results-file ./metrics/eval.json --results-format json
roar put output/resnet18-fashion-mnist/last.pth.tar hf://reproducible-ai/timm-classifier --public --no-tag -m 'resnet18 trained from scratch on Fashion-MNIST (28px, 5 epochs, batch 256) with timm/train.py — TRUNCATED run, not converged; published with its held-out top-1 metrics'

