#!/usr/bin/env bash
# Reproduction script for lineage d88d877377a9d97f3213bd3604c0d1a2e6685374d98d374d81bd1325d0bf9a9b
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
# Publish (roar put) steps are omitted (--no-puts).
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/OLMo-core reproduction
cd reproduction
git checkout 790e8d09bfe0ba2b64618a1321fc2a3320d3dfc2

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# Build tool packages (apt; requires sudo): binutils
# System packages (apt; requires sudo): ibverbs-providers libfabric1-aws libffi8 libgdrapi libhwloc15 libibverbs1 libnccl-ofi libnl-route-3-200 libsqlite3-0 libssl3 libstdc++6 libudev1 libuuid1
pip install GitPython==3.1.61 Jinja2==3.1.6 MarkupSafe==3.0.3 PyYAML==6.0.3 Pygments==2.21.0 ai2-olmo-core==2.6.0 anyio==4.15.0 beaker-gantry==3.7.0 beaker-py==2.7.2 bettermap==1.3.1 boto3==1.43.87 botocore==1.43.87 cached_path==1.8.10 certifi==2026.7.22 charset-normalizer==3.5.1 click==8.5.0 cryptography==50.0.1 cuda-bindings==13.3.1 cuda-pathfinder==1.8.1 dataclass-extensions==0.5.0 dill==0.4.1 filelock==3.32.5 gitdb==4.0.12 google-api-core==2.34.0 google-auth==2.57.0 google-cloud-compute==1.51.0 google-cloud-core==2.7.0 google-cloud-storage==3.13.1 google-resumable-media==2.10.2 googleapis-common-protos==1.75.2 grpcio-status==1.83.1 grpcio==1.83.1 h11==0.16.0 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.30.0 idna==3.19 jmespath==1.1.0 mpmath==1.3.0 networkx==3.6.1 numpy==2.5.2 packaging==26.3 protobuf==6.33.6 python-dateutil==2.9.0.post0 regex==2026.9.3 requests==2.34.2 rich==13.9.4 s3transfer==0.19.2 safetensors==0.8.0 six==1.17.0 smmap==5.0.3 sympy==1.14.0 tokenizers==0.23.2 torch==2.13.0 tqdm==4.70.0 transformers==5.16.1 triton==3.7.1 typing_extensions==4.16.0 urllib3==2.7.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run python reproduction/row027_olmo3_ladder.py prepare-data --output data/dolma3_tokens.npy --manifest data/manifest.json --num-tokens 32768
roar run python -m torch.distributed.run --standalone --nproc-per-node=1 reproduction/row027_olmo3_ladder.py train --data data/dolma3_tokens.npy --output-dir outputs
roar run python reproduction/row027_olmo3_ladder.py package-checkpoint --checkpoint outputs/3B/step1 --output artifacts/olmo3-3b-step1.tar

