#!/usr/bin/env bash
# Reproduction script for lineage c2ffb3ef71e1f4dafd87e0fc95ef172addb0e4f9b7ebc490360dbf572d60d0cc
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
# Publish (roar put) steps are omitted (--no-puts).
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/minGPT reproduction
cd reproduction
git checkout e2108219da054285dbe3f0a26ff9803434251f13

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# System packages (apt; requires sudo): libffi8 libsqlite3-0 libssl3 libstdc++6 libuuid1
pip install PyYAML==6.0.3 Pygments==2.20.0 annotated-types==0.7.0 anyio==4.13.0 blake3==1.0.9 brotli==1.2.0 certifi==2026.4.22 click==8.4.2 cryptography==46.0.7 defusedxml==0.7.1 dill==0.4.1 filelock==3.29.0 fsspec==2026.3.0 gradio_client==2.5.0 h11==0.16.0 httpcore==1.0.9 httpx==0.28.1 huggingface_hub==1.25.1 idna==3.13 mpmath==1.3.0 networkx==3.6.1 numpy==2.4.4 nvidia-ml-py==13.595.45 orjson==3.11.9 packaging==26.2 pillow==12.2.0 pydantic==2.13.3 pydantic_core==2.46.3 python-multipart==0.0.32 rich==14.3.4 starlette==1.0.0 sympy==1.14.0 tabulate==0.10.0 torch==2.7.0 tqdm==4.67.3 trackio==0.33.0 triton==3.3.0 typing-inspection==0.4.2 typing_extensions==4.15.0 uvicorn==0.46.0 watchfiles==1.2.0 wcwidth==0.6.0 zstandard==0.25.0

# 3. Run the pipeline (recorded order)
roar run --wandb-to-trackio python -m projects.adder.adder --trainer.max_iters=3000 --trainer.num_workers=0

