#!/usr/bin/env bash
# Reproduction script for lineage 5d5c04ca31854eb2678552dcf24f96e39d77449513643e7e0a2e3ee4f6399673
# Generated by `roar reproduce --script`. Dry & editable: review the steps
# (e.g. change --device, or run on your own infra) before executing.
# Publish (roar put) steps are omitted (--no-puts).
set -euo pipefail

# 1. Clone the recorded code at its exact commit
git clone https://github.com/reproducible-ai/GloVe reproduction
cd reproduction
git checkout f0390184aa3a35071be2d8504302d6905416daef

# 2. Recreate the Python environment
python3 -m venv .venv
source .venv/bin/activate
# Build tool packages (apt; requires sudo): binutils make
# System packages (apt; requires sudo): libffi8 libsqlite3-0 libssl3 libuuid1
pip install numpy==1.26.4

# 3. Run the pipeline (recorded order)
roar run sh -c 'curl -fsSL https://mattmahoney.net/dc/text8.zip -o data/text8.zip && echo a6640522afe85d1963ad56c05b0ede0a0c000dddc9671758a6cc09b7a38e5232 data/text8.zip | sha256sum -c - && unzip -p data/text8.zip text8 > data/text8 && echo 6e890197040d37d85beb962ae1f041ff1d9a9ca8d20c7d99c85027eebf51dca7 data/text8 | sha256sum -c -'
roar run make
roar run sh -c 'build/vocab_count -min-count 5 -verbose 2 < data/text8 > work/vocab.txt'
roar run sh -c 'build/cooccur -memory 4.0 -vocab-file work/vocab.txt -verbose 2 -window-size 15 < data/text8 > work/cooccurrence.bin'
roar run sh -c 'build/shuffle -memory 4.0 -verbose 2 < work/cooccurrence.bin > work/cooccurrence.shuf.bin'
roar run build/glove -save-file outputs/vectors -threads 8 -input-file work/cooccurrence.shuf.bin -x-max 10 -iter 15 -vector-size 50 -binary 2 -vocab-file work/vocab.txt -verbose 2
roar run sh -c 'python eval/python/evaluate.py --vocab_file work/vocab.txt --vectors_file outputs/vectors.txt > outputs/evaluation.txt'
roar run tar -czf outputs/glove-text8.tar.gz outputs/vectors.bin outputs/vectors.txt outputs/evaluation.txt work/vocab.txt

